1 - SELECT first_name,last_name FROM employees;
2-  SELECT emp_no,first_name FROM employees;
3 - SELECT DISTINCT first_name FROM employees;
4 - SELECT DISTINCT first_name FROM employees ORDER BY first_name;
5 - SELECT DISTINCT first_name FROM employees ORDER BY first_name DESC;
6 - SELECT DISTINCT first_name FROM employees ORDER BY first_name ASC;
7 - SELECT first_name,last_name FROM employees; ??
8 - SELECT DISTINCT first_name, last_name FROM employees ORDER BY first_name, last_name;
11 - SELECT first_name, last_name FROM employees LIMIT 100;
12 - SELECT first_name, last_name, emp_no FROM employees ORDER BY emp_no LIMIT 100;
13 - SELECT first_name, last_name, emp_no FROM employees ORDER BY emp_no ASC LIMIT 100;
14 - SELECT first_name, last_name, emp_no FROM employees ORDER BY emp_no DESC LIMIT 100;
15 - SELECT first_name, last_name, emp_no FROM employees WHERE first_name = "Basil";
16 - SELECT * FROM employees WHERE first_name = "Basil" AND gender = 'M';
17 - SELECT * FROM employees WHERE first_name = "Basil" AND gender != 'M';
SELECT * FROM employees WHERE first_name = "Basil" AND gender <> 'M';
18 - SELECT * FROM employees WHERE first_name = 'Basil' AND last_name = 'Strooper' AND gender = 'M';
19 - SELECT * FROM employees WHERE first_name LIKE "Crist%";
20 - SELECT * FROM employees WHERE first_name LIKE "%zette";
21 - SELECT * FROM employees WHERE first_name LIKE "%zette" AND gender = 'M';
22 - SELECT * FROM employees WHERE first_name LIKE "%arvi%";
23 - SELECT * FROM employees WHERE first_name LIKE "%arvi%" AND gender = 'M';
24 - SELECT * FROM employees WHERE first_name ="Yinghua" OR first_name ="Elvis";
25 - SELECT * FROM employees WHERE gender = 'M' AND (first_name ="Yinghua" OR first_name ="Elvis");
26 - SELECT * FROM employees WHERE emp_no = 14037;
27 - SELECT first_name, last_name FROM employees WHERE emp_no = 14037;
28 - SELECT * FROM employees WHERE emp_no IN (15037,14039,16039);
29 - SELECT * FROM employees WHERE emp_no BETWEEN 14037 AND 14047;
30 - SELECT * FROM employees WHERE employees.emp_no >= 14037 AND employees.emp_no <= 14047;
31 - SELECT * FROM employees WHERE first_name LIKE "Crist%" AND emp_no > 485733;
32 - SELECT * FROM employees WHERE first_name LIKE "Crist%" AND emp_no >= 485733;
33 - SELECT * FROM employees WHERE first_name LIKE "%Crist%" AND emp_no < 37126;
34 - SELECT * FROM employees WHERE first_name LIKE "%Crist%" AND emp_no <=  37126;
35 - SELECT * FROM employees WHERE emp_no IN (494831, 479832, 599833, 499832) AND gender IN ('M','F');
36 - SELECT * FROM employees WHERE emp_no IN (494831, 479832, 599833, 499832) AND gender IN ('M','F') LIMIT 10;
39 - SELECT country.Code,country.Name,countrylanguage.Language FROM country INNER JOIN countrylanguage ON country.Code= countrylanguage.CountryCode WHERE Language = "Dutch";
